name: DiffableDataSource
options:
  deploymentTarget:
    iOS: "15.0"
  bundleIdPrefix: home
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
targets:
  DiffableDataSource:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - DiffableDataSource
    dependencies:
      - package: SnapKit
